version: '3'
services:
  scrapy:
    command: /start
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    depends_on:
      - selenium
    volumes:
      - .:/app
      - ./logs:/app/logs
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - "5900:5900"
    shm_size: 128M
